-- =============================================================================
-- CrowdEye AI - Database Migration 001
-- Initial Schema & Row Level Security (RLS) Configuration
-- Single Source of Truth for Supabase PostgreSQL
-- =============================================================================

-- Enable UUID extension if not already available
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- -----------------------------------------------------------------------------
-- 1. USERS TABLE
-- Stores security personnel, operators, and administrators
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL DEFAULT 'security', -- 'admin', 'security', 'operator'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 2. EVENTS TABLE
-- Large public gatherings, concerts, sports events, festivals
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_name TEXT NOT NULL,
    location TEXT NOT NULL,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT NOT NULL DEFAULT 'SCHEDULED' -- 'SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED'
);

-- -----------------------------------------------------------------------------
-- 3. CAMERAS TABLE
-- CCTV/RTSP cameras deployed at various zones across the event venue
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cameras (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id UUID NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    camera_name TEXT NOT NULL,
    zone TEXT NOT NULL, -- e.g., 'Main Gate', 'North Corridor', 'Stage Front'
    stream_url TEXT
);

-- -----------------------------------------------------------------------------
-- 4. CROWD_LOGS TABLE
-- Time-series telemetry generated by AI perception engine
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.crowd_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    camera_id UUID NOT NULL REFERENCES public.cameras(id) ON DELETE CASCADE,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    people_count INTEGER NOT NULL DEFAULT 0,
    density FLOAT NOT NULL DEFAULT 0.0, -- people per square meter
    risk_score FLOAT NOT NULL DEFAULT 0.0, -- 0.0 (Safe) to 1.0 (Critical)
    status TEXT NOT NULL DEFAULT 'NORMAL' -- 'NORMAL', 'MODERATE', 'CONGESTED', 'CRITICAL'
);

-- -----------------------------------------------------------------------------
-- 5. ALERTS TABLE
-- Real-time security alarms, bottlenecks, stampede warnings
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id UUID NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    zone TEXT NOT NULL,
    message TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'MEDIUM', -- 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    resolved BOOLEAN NOT NULL DEFAULT FALSE
);

-- -----------------------------------------------------------------------------
-- PERFORMANCE INDEXES
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_cameras_event_id ON public.cameras(event_id);
CREATE INDEX IF NOT EXISTS idx_crowd_logs_camera_id ON public.crowd_logs(camera_id);
CREATE INDEX IF NOT EXISTS idx_crowd_logs_timestamp ON public.crowd_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_event_id ON public.alerts(event_id);
CREATE INDEX IF NOT EXISTS idx_alerts_resolved ON public.alerts(resolved);

-- =============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =============================================================================

-- Enable RLS across all tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cameras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crowd_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------------------------------------
-- USERS POLICIES
-- Authenticated users can view user profiles
-- -----------------------------------------------------------------------------
CREATE POLICY "Allow authenticated users to read profiles"
    ON public.users
    FOR SELECT
    TO authenticated
    USING (true);

-- -----------------------------------------------------------------------------
-- EVENTS POLICIES
-- Authenticated users can read events
-- -----------------------------------------------------------------------------
CREATE POLICY "Allow authenticated users to read events"
    ON public.events
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Allow service_role full access to events"
    ON public.events
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- -----------------------------------------------------------------------------
-- CAMERAS POLICIES
-- Authenticated users can read camera streams and configurations
-- -----------------------------------------------------------------------------
CREATE POLICY "Allow authenticated users to read cameras"
    ON public.cameras
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Allow service_role full access to cameras"
    ON public.cameras
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- -----------------------------------------------------------------------------
-- CROWD_LOGS POLICIES
-- - Authenticated users can READ crowd telemetry logs
-- - Only backend service key (service_role) can INSERT AI generated telemetry
-- -----------------------------------------------------------------------------
CREATE POLICY "Allow authenticated users to read crowd_logs"
    ON public.crowd_logs
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Allow service_role to insert crowd_logs"
    ON public.crowd_logs
    FOR INSERT
    TO service_role
    WITH CHECK (true);

CREATE POLICY "Allow service_role full access to crowd_logs"
    ON public.crowd_logs
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- -----------------------------------------------------------------------------
-- ALERTS POLICIES
-- - Authenticated users can READ alerts
-- - Only backend service key (service_role) can CREATE alerts
-- - Service role or security personnel can update resolved state
-- -----------------------------------------------------------------------------
CREATE POLICY "Allow authenticated users to read alerts"
    ON public.alerts
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Allow service_role to insert alerts"
    ON public.alerts
    FOR INSERT
    TO service_role
    WITH CHECK (true);

CREATE POLICY "Allow service_role to update alerts"
    ON public.alerts
    FOR UPDATE
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow service_role full access to alerts"
    ON public.alerts
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Ensure anon/public cannot insert into crowd_logs or alerts
-- (In Supabase, anon is blocked by default when no policy matches)
